server:
  port: 4004

auth:
  service:
    url: http://localhost:4008

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service-route
              uri: http://localhost:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1
                - JwtValidation

            - id: api-docs-patient-service-route
              uri: http://localhost:4000
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients, /v3/api-docs

            - id: billing-service-route
              uri: http://localhost:4001
              predicates:
                - Path=/api/bills/**

            - id: auth-service-route
              uri: http://localhost:4008
              predicates:
                - Path=/auth/**
              filters:
                  - StripPrefix=1

            - id: api-docs-auth-service-route
              uri: http://localhost:4008
              predicates:
                - Path=/api-docs/auth
              filters:
                - RewritePath=/api-docs/auth, /v3/api-docs