server:
  port: 4004

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service-route
              uri: http://localhost:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1
            - id: billing-service-route
              uri: http://localhost:4001
              predicates:
                - Path=/api/bills/**